name: Pipeline

on: [push]

jobs:
  build_job:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container:
      image: kselyunin/python3.9-sphinx-rtd:v0.1
    env:
      VERSION_MAJOR: 0
      VERSION_MINOR: 0
      DOCS_VERSION: 0.0.0
      PROJECT: rsl_sphinx_docs

    steps:
      - uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - uses: actions/checkout@v2
        with:
          repository: selyunin/cyton_gamma_300_docs
          path: 'cyton_gamma_300_docs_src'
          ref: ${{ env.GITHUB_SHA }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        with:
          repository: selyunin/cyton_gamma_300_docs
          path: 'cyton_gamma_300_docs_gen'
          ref: gh-pages
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Read version number
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        run: |
          VERSION_MAJOR=`sed -n '1p' cyton_gamma_300_docs_src/VERSION | grep -oEi ":.*" | grep -oEi "[[:alnum:]]+"`
          VERSION_MINOR=`sed -n '2p' cyton_gamma_300_docs_src/VERSION | grep -oEi ":.*" | grep -oEi "[[:alnum:]]+"`
          DOCS_VERSION=${MAJOR}.${MINOR}.${BUILD_NUMBER}
          echo "VERSION_MAJOR=${VERSION_MAJOR}" >> $GITHUB_ENV
          echo "VERSION_MINOR=${VERSION_MINOR}" >> $GITHUB_ENV
          echo "DOCS_VERSION=${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_NUMBER}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Build documentation
        run: |
          ls -la .
          pwd
          ls -la cyton_gamma_300_docs_src
          cd cyton_gamma_300_docs_src && sphinx-build -b html source build/html
          rm -rf ../cyton_gamma_300_docs_gen/docs
          mkdir -p ../cyton_gamma_300_docs_gen/docs
          cp -r build/html/* ../cyton_gamma_300_docs_gen/docs
          cd ../cyton_gamma_300_docs_gen/docs && touch .nojekyll && cd ..

      - name: Commit newly generated sources
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '.'

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
          branch: gh-pages

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          cwd: './cyton_gamma_300_docs_gen'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Docs v${{ env.DOCS_VERSION }}'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          pull_strategy: 'NO-PULL'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          remove: ''

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
          signoff: true

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          tag: 'v${{ env.DOCS_VERSION }} --force'